apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cache
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-cache
spec:
  replicas: {{ .Values.cache.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cache
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cache
    spec:
      containers:
      - name: {{ .Release.Name }}-multitool
        image: {{ .Values.cache.image }}
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          value: "80"
        - name: HTTPS_PORT
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cache-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-cache
  ports:
  - port: {{ .Values.cache.service.port }}
    targetPort: 80
  type: {{ .Values.cache.service.type }}