apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
      - name: {{ .Release.Name }}-multitool
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          value: "80"
        - name: HTTPS_PORT
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
  type: {{ .Values.frontend.service.type }}