apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - name: {{ .Release.Name }}-backend
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
