apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init-app
  template:
    metadata:
      labels:
        app: nginx-init-app
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox:1.35
        command: ['sh', '-c', 'until nslookup nginx-init-service.default.svc.cluster.local; do echo waiting for service; sleep 2; done; echo Service is ready!']
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
