apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage # ДОПОЛНИТЕ: Имя StorageClass
provisioner: microk8s.io/hostpath # ИНФОРМАЦИЯ: Нет автоматического развёртывания
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim # ДОПОЛНИТЕ: Имя PVC
spec:
  storageClassName: local-storage  # ДОПОЛНИТЕ: Имя StorageClass. Должно совпадать с объявленным ранее
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # ДОПОЛНИТЕ: Какой объём хранилища вы хотите передать в контейнер. Должно быть меньше или равно параметру storage из PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1 # ЗАДАНИЕ: Укажите количество реплик
  selector:
    matchLabels:
      app: data-exchange-pvc-app # ДОПОЛНИТЕ: Метка для селектора
  template:
    metadata:
      labels:
        app: data-exchange-pvc-app # ПОВТОРИТЕ: Метка из selector.matchLabels
    spec:
      containers:
      - name: busybox # ДОПОЛНИТЕ: Имя первого контейнера
        image: busybox
        command: ["/bin/sh", "-c"] 
        args: 
          - |
            while true; do
              echo "Data from busybox at $(date)" >> /output/file.txt;
              sleep 5;
            done
        volumeMounts:
        - name: vol # ДОПОЛНИТЕ: Имя монтируемого раздела. Должно совпадать с именем хранилища, объявленного на уровне пода
          mountPath: /output # КЛЮЧЕВОЕ: Путь монтирования хранилища внутри контейнера 1
      - name: multitool # ДОПОЛНИТЕ: Имя второго контейнера
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args: ["tail -f /input/file.txt"] # КЛЮЧЕВОЕ: Команда для чтения данных из файла, расположенного в директории, указанной в volumeMounts контейнера
        volumeMounts:
        - name: vol # ДОПОЛНИТЕ: Имя монтируемого раздела. Должно совпадать с именем эфемерного хранилища, объявленного на уровне пода
          mountPath: /input # КЛЮЧЕВОЕ: Путь монтирования эфемерного хранилища внутри контейнера 2
      volumes:
      - name: vol # ДОПОЛНИТЕ: Имя монтируемого раздела хранилища
        persistentVolumeClaim:
          claimName: volume-claim # КЛЮЧЕВОЕ: Совпадает с именем PVC объявленного ранее