apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-app
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-multitool-app
  template:
    metadata:
      labels:
        app: nginx-multitool-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.30
        ports:
        - containerPort: 80
        
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
#        command: ["sh", "-c", "sleep infinity"] # Добавляем команду
        env: 
          - name: HTTP_PORT
            value: "1180"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-init-service
spec:
  selector:
    app: nginx-init-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP